In [ ]:
import numpy as np
import scipy.linalg
from scipy import signal
from scipy.sparse.linalg import cg, eigs

np.set_printoptions(precision=4, suppress=True)
birthday = np.array([2., 0., 0., 4., 0., 8., 1., 1.])
a = np.array([
    [2., 0., 0., 4., 0.],
    [8., 1., 1., 2., 0.],
    [0., 4., 0., 8., 1.],
    [1., 2., 0., 0., 4.],
    [0., 8., 1., 1., 2.],
    [0., 0., 4., 0., 8.]
])

M = np.array([
    [2., 0., 0., 4.],
    [0., 8., 1., 1.],
    [4., 0., 8., 1.],
    [1., 1., 2., 0.]
])

A = M.T @ M + np.eye(4)
B = np.diag([2., 4., 8., 11.])
b = np.array([2., 0., 4., 8.])
v = birthday.copy()

print("Birthday digits:", birthday)
print("General birthday matrix a:\n", a)
print("Square birthday matrix A:\n", A)
print("Number of dimensions using np.ndim(a):", np.ndim(a))
print("Number of dimensions using a.ndim:", a.ndim)
print("Number of elements using np.size(a):", np.size(a))
print("Number of elements using a.size:", a.size)
print("Shape using np.shape(a):", np.shape(a))
print("Shape using a.shape:", a.shape)

n = 2
print("Size of the second dimension:", a.shape[n - 1])

print(
    "Two-by-three birthday array:\n",
    np.array([[2., 0., 0.], [4., 8., 11.]])
)

a1 = np.array([[2.]])
b1 = np.array([[0.]])
c1 = np.array([[4.]])
d1 = np.array([[8.]])

print("Block matrix:\n", np.block([[a1, b1], [c1, d1]]))
print("Last element of the birthday vector:", v[-1])
print("Element in the second row and fifth column:", a[1, 4])
print("Second row using a[1]:", a[1])
print("Second row using a[1, :]:", a[1, :])
print("First five rows using a[0:5]:\n", a[0:5])
print("First five rows using a[:5]:\n", a[:5])
print("First five rows using a[0:5, :]:\n", a[0:5, :])

a_nan = a.copy()
a_nan[0, 1] = np.nan

print("Maximum element using a.max():", a.max())
print("Maximum element ignoring NaN:", np.nanmax(a_nan))
print("Maximum value in each column:", a.max(axis=0))
print("Maximum value in each row:", a.max(axis=1))
print("Element-wise maximum of a and 4:\n", np.maximum(a, 4))
print("Vector norm using square root and dot product:", np.sqrt(v @ v))
print("Vector norm using np.linalg.norm:", np.linalg.norm(v))

bool_a = birthday > 0
bool_b = birthday % 2 == 0

print("Element-wise logical AND:", np.logical_and(bool_a, bool_b))
print("Element-wise logical OR:", np.logical_or(bool_a, bool_b))

int_a = np.array([2, 0, 0, 4])
int_b = np.array([0, 8, 1, 1])

print("Element-wise bitwise AND:", int_a & int_b)
print("Element-wise bitwise OR:", int_a | int_b)
print("Inverse of A:\n", scipy.linalg.inv(A))
print("Pseudoinverse of A:\n", scipy.linalg.pinv(A))
print("Rank of A:", np.linalg.matrix_rank(A))

x = scipy.linalg.solve(A, b)

print("Solution of A x = b:", x)
print("Verification of A x:\n", A @ x)

right_b = np.array([
    [2., 0., 0., 4.],
    [0., 8., 1., 1.]
])

right_x = scipy.linalg.solve(A.T, right_b.T).T

print("Solution of X A = right_b:\n", right_x)
print("Verification of X A:\n", right_x @ A)

U, S, Vh = scipy.linalg.svd(A)
V = Vh.T

print("Left singular vectors U:\n", U)
print("Singular values S:", S)
print("Right singular vectors V:\n", V)
print("SVD reconstruction:\n", U @ np.diag(S) @ V.T)

R_cholesky = scipy.linalg.cholesky(A)

print("Cholesky factor:\n", R_cholesky)
print("Cholesky reconstruction:\n", R_cholesky.T @ R_cholesky)

D, V_eig = scipy.linalg.eig(A)

print("Eigenvalues of A:", D)
print("Eigenvectors of A:\n", V_eig)

D_general, V_general = scipy.linalg.eig(A, B)

print("Generalized eigenvalues:", D_general)
print("Generalized eigenvectors:\n", V_general)

large_A = np.diag(birthday + 1)
D_large, V_large = eigs(large_A, k=3)

print("Three eigenvalues from eigs:", D_large)
print("Corresponding eigenvectors:\n", V_large)

Q, R = scipy.linalg.qr(A)

print("Orthogonal matrix Q:\n", Q)
print("Upper triangular matrix R:\n", R)
print("QR reconstruction:\n", Q @ R)

P, L, U_lu = scipy.linalg.lu(A)

print("Permutation matrix P:\n", P)
print("Lower triangular matrix L:\n", L)
print("Upper triangular matrix U:\n", U_lu)
print("LU reconstruction:\n", P @ L @ U_lu)

x_cg, info = cg(A, b)

print("Conjugate gradient solution:", x_cg)
print("Conjugate gradient status:", info)

fft_result = np.fft.fft(v)

print("Fourier transform of the birthday vector:", fft_result)
print("Inverse Fourier transform:", np.fft.ifft(fft_result))
print("Column-wise sorting using np.sort:\n", np.sort(a, axis=0))

a_column_sorted = a.copy()
a_column_sorted.sort(axis=0)

print("Column-wise sorting using array.sort:\n", a_column_sorted)
print("Row-wise sorting using np.sort:\n", np.sort(a, axis=1))

a_row_sorted = a.copy()
a_row_sorted.sort(axis=1)

print("Row-wise sorting using array.sort:\n", a_row_sorted)

indices = np.argsort(a[:, 0])
sorted_rows = a[indices, :]

print("Indices for sorting rows by the first column:", indices)
print("Rows sorted by the first column:\n", sorted_rows)

Z = np.column_stack((np.ones(8), np.arange(1, 9)))
y = birthday.copy()
regression_x = scipy.linalg.lstsq(Z, y)[0]

print("Least-squares regression coefficients:", regression_x)

q = 2
resampled_signal = signal.resample(
    v,
    int(np.ceil(len(v) / q))
)

print("Resampled birthday signal:", resampled_signal)
print("Unique birthday digits:", np.unique(birthday))

singleton_array = birthday.reshape(1, 8, 1)

print("Shape before squeezing:", singleton_array.shape)
print("Shape after squeezing:", singleton_array.squeeze().shape)

Birthday digits: [2. 0. 0. 4. 0. 8. 1. 1.]
General birthday matrix a:
 [[2. 0. 0. 4. 0.]
 [8. 1. 1. 2. 0.]
 [0. 4. 0. 8. 1.]
 [1. 2. 0. 0. 4.]
 [0. 8. 1. 1. 2.]
 [0. 0. 4. 0. 8.]]
Square birthday matrix A:
 [[22.  1. 34. 12.]
 [ 1. 66. 10.  8.]
 [34. 10. 70.  9.]
 [12.  8.  9. 19.]]
Number of dimensions using np.ndim(a): 2
Number of dimensions using a.ndim: 2
Number of elements using np.size(a): 30
Number of elements using a.size: 30
Shape using np.shape(a): (6, 5)
Shape using a.shape: (6, 5)
Size of the second dimension: 5
Two-by-three birthday array:
 [[ 2.  0.  0.]
 [ 4.  8. 11.]]
Block matrix:
 [[2. 0.]
 [4. 8.]]
Last element of the birthday vector: 1.0
Element in the second row and fifth column: 0.0
Second row using a[1]: [8. 1. 1. 2. 0.]
Second row using a[1, :]: [8. 1. 1. 2. 0.]
First five rows using a[0:5]:
 [[2. 0. 0. 4. 0.]
 [8. 1. 1. 2. 0.]
 [0. 4. 0. 8. 1.]
 [1. 2. 0. 0. 4.]
 [0. 8. 1. 1. 2.]]
First five rows using a[:5]:
 [[2. 0. 0. 4. 0.]
 [8. 1. 1. 2. 0.]
 [0. 4. 0. 8. 1