In [ ]:
import numpy as np

birthday = np.array([2, 0, 0, 4, 0, 8, 1, 1])
birthday_matrix = birthday.reshape(2, 4)

print("Birthday array:")
print(birthday)
print("Birthday matrix:")
print(birthday_matrix)
print("Array type:")
print(type(birthday))
print("Array shape:")
print(birthday.shape)
print("Matrix shape:")
print(birthday_matrix.shape)
print("Zero matrix:")
print(np.zeros((2, 4)))
print("One matrix:")
print(np.ones((2, 4)))
print("Constant matrix:")
print(np.full((2, 4), 8))
print("Identity matrix:")
print(np.eye(4))

Birthday array:
[2 0 0 4 0 8 1 1]
Birthday matrix:
[[2 0 0 4]
 [0 8 1 1]]
Array type:
<class 'numpy.ndarray'>
Array shape:
(8,)
Matrix shape:
(2, 4)
Zero matrix:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
One matrix:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Constant matrix:
[[8 8 8 8]
 [8 8 8 8]]
Identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [2]:
print("First element:")
print(birthday[0])

print("Last element:")
print(birthday[-1])

print("First four elements:")
print(birthday[:4])

print("First row:")
print(birthday_matrix[0, :])

print("Second row:")
print(birthday_matrix[1, :])

print("First two columns:")
print(birthday_matrix[:, :2])

print("Element in the second row and third column:")
print(birthday_matrix[1, 2])

print("Elements greater than one:")
print(birthday_matrix[birthday_matrix > 1])

print("Boolean index matrix:")
print(birthday_matrix > 1)

First element:
2
Last element:
1
First four elements:
[2 0 0 4]
First row:
[2 0 0 4]
Second row:
[0 8 1 1]
First two columns:
[[2 0]
 [0 8]]
Element in the second row and third column:
1
Elements greater than one:
[2 4 8]
Boolean index matrix:
[[ True False False  True]
 [False  True False False]]


In [3]:
integer_array = np.array([2, 0, 0, 4, 0, 8, 1, 1], dtype=np.int64)
float_array = np.array([2, 0, 0, 4, 0, 8, 1, 1], dtype=np.float64)
boolean_array = birthday > 0

print("Integer array:")
print(integer_array)

print("Integer data type:")
print(integer_array.dtype)

print("Floating-point array:")
print(float_array)

print("Floating-point data type:")
print(float_array.dtype)

print("Boolean array:")
print(boolean_array)

print("Boolean data type:")
print(boolean_array.dtype)

Integer array:
[2 0 0 4 0 8 1 1]
Integer data type:
int64
Floating-point array:
[2. 0. 0. 4. 0. 8. 1. 1.]
Floating-point data type:
float64
Boolean array:
[ True False False  True False  True  True  True]
Boolean data type:
bool


In [4]:
x = birthday_matrix.astype(float)

y = np.array([
    [1., 2., 3., 4.],
    [5., 6., 7., 8.]
])

print("Element-wise addition:")
print(x + y)

print("Element-wise subtraction:")
print(x - y)

print("Element-wise multiplication:")
print(x * y)

print("Element-wise division:")
print(x / y)

print("Square root:")
print(np.sqrt(y))

print("Matrix multiplication:")
print(x @ y.T)

print("Sum of all elements:")
print(np.sum(x))

print("Sum of each column:")
print(np.sum(x, axis=0))

print("Sum of each row:")
print(np.sum(x, axis=1))

print("Transpose:")
print(x.T)

Element-wise addition:
[[ 3.  2.  3.  8.]
 [ 5. 14.  8.  9.]]
Element-wise subtraction:
[[ 1. -2. -3.  0.]
 [-5.  2. -6. -7.]]
Element-wise multiplication:
[[ 2.  0.  0. 16.]
 [ 0. 48.  7.  8.]]
Element-wise division:
[[2.         0.         0.         1.        ]
 [0.         1.33333333 0.14285714 0.125     ]]
Square root:
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]]
Matrix multiplication:
[[18. 42.]
 [23. 63.]]
Sum of all elements:
16.0
Sum of each column:
[2. 8. 1. 5.]
Sum of each row:
[ 6. 10.]
Transpose:
[[2. 0.]
 [0. 8.]
 [0. 1.]
 [4. 1.]]


In [5]:
row_offset = np.array([1., 2., 3., 4.])
row_result = x + row_offset

print("Original matrix:")
print(x)

print("Row offset:")
print(row_offset)

print("Result after row broadcasting:")
print(row_result)

column_offset = np.array([[10.], [20.]])
column_result = x + column_offset

print("Column offset:")
print(column_offset)

print("Result after column broadcasting:")
print(column_result)

Original matrix:
[[2. 0. 0. 4.]
 [0. 8. 1. 1.]]
Row offset:
[1. 2. 3. 4.]
Result after row broadcasting:
[[ 3.  2.  3.  8.]
 [ 1. 10.  4.  5.]]
Column offset:
[[10.]
 [20.]]
Result after column broadcasting:
[[12. 10. 10. 14.]
 [20. 28. 21. 21.]]
